version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./magento:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
    restart: unless-stopped

  php:
    image: php:8.1-fpm
    volumes:
      - ./magento:/var/www/html
      - ./app:/var/www/html/app
    depends_on:
      - mysql
    restart: unless-stopped
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libicu-dev libxml2-dev libxslt1-dev libzip-dev unzip curl wget &&
      docker-php-ext-configure gd --with-freetype --with-jpeg &&
      docker-php-ext-install -j\$$(nproc) gd intl pdo_mysql soap xsl zip bcmath sockets &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      if [ ! -d '/var/www/html/vendor' ]; then
        cd /var/www/html &&
        composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.6 . &&
        find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} + &&
        find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} + &&
        chown -R :www-data . &&
        chmod u+x bin/magento
      fi &&
      php-fpm
      "

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento123
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
